using System.Text;
using System.Text.Json;
using Op7PortScanner.Models;

namespace Op7PortScanner.Services;

// ──────────────────────────────────────────────────────────────────────────────
//  ExportService — saves scan results in three different formats.
//
//  TXT  — human-readable report, great for sharing or printing
//  CSV  — spreadsheet-friendly, import into Excel / Google Sheets
//  JSON — machine-readable, useful for scripting or integration with other tools
//
//  All methods are async so the UI never freezes while writing large files.
// ──────────────────────────────────────────────────────────────────────────────
public static class ExportService
{
    // Shared JSON options — reused across calls to avoid re-allocating options.
    private static readonly JsonSerializerOptions JsonOpts = new() { WriteIndented = true };

    #region TXT Export

    /// <summary>
    /// Saves a plain-text report designed to be read by a human.
    /// Includes a header with scan metadata and a table of open ports.
    /// </summary>
    public static async Task SaveTxtAsync(
        string          path,
        string          host,
        int             totalScanned,
        List<ScanResult> openPorts)
    {
        var sb = new StringBuilder();

        // Header block
        sb.AppendLine("════════════════════════════════════════════════════════════");
        sb.AppendLine("              op7 port scanner v3 — SCAN REPORT");
        sb.AppendLine("════════════════════════════════════════════════════════════");
        sb.AppendLine($"  Host      : {host}");
        sb.AppendLine($"  Date      : {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($"  Scanned   : {totalScanned} ports");
        sb.AppendLine($"  Open      : {openPorts.Count} port(s)");
        sb.AppendLine("────────────────────────────────────────────────────────────");

        // Column headers
        sb.AppendLine($"  {"TIME",-10}  {"PORT",-6}  {"SERVICE",-16}  BANNER / INFO");
        sb.AppendLine("────────────────────────────────────────────────────────────");

        // One line per open port
        foreach (var result in openPorts)
        {
            // Truncate banner so the table doesn't wrap awkwardly in a text editor.
            string banner = result.Banner.Length > 50
                ? result.Banner[..50] + "…"
                : result.Banner;

            sb.AppendLine($"  {result.Timestamp:HH:mm:ss}    {result.Port,-6}  {result.Service,-16}  {banner}");
        }

        sb.AppendLine("════════════════════════════════════════════════════════════");
        sb.AppendLine($"  Generated by op7 port scanner v3 — {DateTime.Now:yyyy-MM-dd}");

        await File.WriteAllTextAsync(path, sb.ToString(), Encoding.UTF8);
    }

    #endregion

    #region CSV Export

    /// <summary>
    /// Saves results as a CSV file with one row per open port.
    /// Fields with commas or quotes are escaped per the CSV standard (RFC 4180).
    /// Import into Excel: File → Open → the .csv file → "Comma" as delimiter.
    /// </summary>
    public static async Task SaveCsvAsync(string path, List<ScanResult> results)
    {
        var sb = new StringBuilder();

        // Header row — these become column names in Excel
        sb.AppendLine("Timestamp,Host,Port,Protocol,Service,Banner,OsGuess,TTL");

        foreach (var r in results)
        {
            // Escape any quotes inside the banner by doubling them (CSV standard).
            string safeBanner = r.Banner.Replace("\"", "\"\"");

            sb.AppendLine(
                $"\"{r.Timestamp:yyyy-MM-dd HH:mm:ss}\"," +
                $"\"{r.Host}\"," +
                $"{r.Port}," +
                $"\"{r.Protocol}\"," +
                $"\"{r.Service}\"," +
                $"\"{safeBanner}\"," +
                $"\"{r.OsGuess}\"," +
                $"{r.Ttl}");
        }

        await File.WriteAllTextAsync(path, sb.ToString(), Encoding.UTF8);
    }

    #endregion

    #region JSON Export

    /// <summary>
    /// Saves results as a JSON file.
    /// The structure includes scan metadata at the top and an array of results.
    /// Example use: feeding into a Python script or a dashboard.
    /// </summary>
    public static async Task SaveJsonAsync(string path, string host, List<ScanResult> results)
    {
        // We build an anonymous object so the JSON structure is clear in the code.
        var document = new
        {
            tool      = "op7 port scanner v3",
            host,
            scanDate  = DateTime.Now.ToString("o"),   // ISO 8601 format
            openCount = results.Count,

            // Each result becomes a clean JSON object (no internal C# names leaked).
            results = results.Select(r => new
            {
                port      = r.Port,
                protocol  = r.Protocol,
                service   = r.Service,
                banner    = r.Banner,
                osGuess   = r.OsGuess,
                ttl       = r.Ttl,
                timestamp = r.Timestamp.ToString("o"),
            })
        };

        string json = JsonSerializer.Serialize(document, JsonOpts);
        await File.WriteAllTextAsync(path, json, Encoding.UTF8);
    }

    #endregion
}
